# Generated by Django 6.0.2 on 2026-02-13 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=20, unique=True)),
                ('genero', models.CharField(max_length=20)),
                ('data_nascimento', models.CharField(blank=True, max_length=30, null=True)),
                ('rua', models.CharField(max_length=120)),
                ('cep', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=100)),
                ('complemento', models.CharField(blank=True, max_length=120, null=True)),
                ('numero', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(max_length=20)),
                ('celular_secundario', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('vinculo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Observacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=50)),
                ('ano', models.CharField(max_length=10)),
                ('combustivel', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=50)),
                ('especie', models.CharField(max_length=50)),
                ('nacionalidade', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguro', models.CharField(max_length=100)),
                ('guincho', models.CharField(max_length=100)),
                ('requerente', models.CharField(max_length=120)),
                ('lista_pecas', models.TextField()),
                ('servico_inicial', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('descricao_geral', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('pecas', models.ManyToManyField(blank=True, to='oficina.peca')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina.veiculo')),
            ],
        ),
    ]
