# Generated by Django 6.0.2 on 2026-10-03 04:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cpf',
            new_name='cpf_cnpj',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='data_criacao',
            new_name='data_cadastro',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='requerente',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='veiculo',
            old_name='especie',
            new_name='marca',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='vinculo',
        ),
        migrations.RemoveField(
            model_name='observacao',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='descricao_geral',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='guincho',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='lista_pecas',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='pecas',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='seguro',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='servico_inicial',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='veiculo',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='nacionalidade',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='uf',
        ),
        migrations.AddField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('PESSOA', 'Pessoa Física'), ('EMPRESA', 'Empresa')], default='PESSOA', max_length=10),
        ),
        migrations.AddField(
            model_name='observacao',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observacoes_oficina', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='peca',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='peca',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peca',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peca',
            name='estoque',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='peca',
            name='estoque_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servico',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peca',
            name='nome',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='oficina.cliente'),
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(editable=False, unique=True)),
                ('solicitacao_cliente', models.TextField()),
                ('motivo_cancelamento', models.TextField(blank=True, null=True)),
                ('demanda_atendida', models.BooleanField(blank=True, null=True)),
                ('motivo_nao_atendida', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ATENDIMENTO', 'Em atendimento'), ('PRONTO', 'Pronto'), ('ENTREGUE', 'Entregue'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20)),
                ('observacao_final', models.TextField(blank=True, null=True)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='oficina.cliente')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='oficina.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to='oficina.peca')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to=settings.AUTH_USER_MODEL)),
                ('ordem_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to='oficina.ordemservico')),
            ],
        ),
        migrations.CreateModel(
            name='ItemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_ordem', to='oficina.servico')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_servico', to='oficina.ordemservico')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_ordem', to='oficina.peca')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_peca', to='oficina.ordemservico')),
            ],
        ),
        migrations.AddField(
            model_name='observacao',
            name='ordem_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observacoes', to='oficina.ordemservico'),
        ),
        migrations.CreateModel(
            name='ParticipacaoMecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participacoes_oficina', to=settings.AUTH_USER_MODEL)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_mecanicos', to='oficina.ordemservico')),
            ],
        ),
    ]
