# Generated by Django 6.0.2 on 2026-10-03 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0002_rename_cpf_cliente_cpf_cnpj_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itempeca',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_peca_oficina', to=settings.AUTH_USER_MODEL),
        ),
    ]
